name: ams_holdcrypto
description: "Sua plataforma completa para acompanhar, negociar e aprender sobre o universo das criptomoedas."
# Previne publicações acidentais no pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependências que seu aplicativo precisa para funcionar.
dependencies:
  flutter:
    sdk: flutter
 
  animate_do: ^3.3.4 # Adicione esta linha

  # Ícones adicionais no padrão Material Design.
  cupertino_icons: ^1.0.2

  # Para fazer requisições HTTP para sua API Gateway. (Equivalente ao Axios)
  http: ^1.2.0

  # Para gerenciamento de estado simples e reativo. (Essencial para UI dinâmica)
  provider: ^6.1.1

  # Para salvar o token JWT de forma segura no dispositivo. (Equivalente ao AsyncStorage)
  flutter_secure_storage: ^9.0.0

  # Para navegação e rotas no aplicativo.
  go_router: ^13.2.0

  # Para criar os gráficos da dashboard e de histórico de moedas.
  fl_chart: ^0.66.2

  # Para formatar datas e valores monetários (ex: R$).
  intl: ^0.19.0

  # Para usar fontes customizadas do Google Fonts facilmente.
  google_fonts: ^6.1.0


# Dependências usadas apenas durante o desenvolvimento.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Um conjunto de regras recomendadas para manter o código limpo e padronizado.
  flutter_lints: ^3.0.1

# A seção a seguir é específica do Flutter.
flutter:
  # Garante que os ícones do Material Design sejam incluídos.
  uses-material-design: true

  # Para adicionar assets (imagens) ao seu aplicativo:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Para adicionar fontes customizadas:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

