name: Workflow DevOps - Projeto Corretora

on:
  push:
    branches:
      - main

jobs:
  mostrar-trabalho:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir mensagem
        run: echo "Workflow executado com sucesso! DevOps presente no projeto."
